<#
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
#>

$max = 4000000



$fibonacci = @(1, 2)

while ($fibonacci[-1] -le $max) {
    $fibonacci += ($fibonacci[-2] + $fibonacci[-1])
    Write-Host $fibonacci[-1]
}

$fibonacci = $fibonacci[0..($fibonacci.Count - 2)]

$fibonacci | Where-Object { ($_ % 2 -eq 0) } | Measure-Object -Sum